<a href="https://colab.research.google.com/github/Jammyeong/MachineLearningClass/blob/main/7thWeek/Tugas_7_ML_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

In [2]:
# Load the uploaded datasets
heart_df = pd.read_csv('/content/drive/MyDrive/smt akhir/ml/HeartDisease.csv')
water_df = pd.read_csv('/content/drive/MyDrive/smt akhir/ml/CitarumWater.csv')
income_df = pd.read_csv('/content/drive/MyDrive/smt akhir/ml/income.csv')

# Display the first few rows of each dataset
print('HEART DISEASE')
print(heart_df.head)
print()
print('CITARUM WATER')
print(water_df.head)
print()
print('INCOME')
print(income_df.head)

HEART DISEASE
<bound method NDFrame.head of      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3
1     67    1   4       160   286    0        2      108      1      1.5
2     67    1   4       120   229    0        2      129      1      2.6
3     37    1   3       130   250    0        0      187      0      3.5
4     41    0   2       130   204    0        2      172      0      1.4
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   45    1   1       110   264    0        0      132      0      1.2
299   68    1   4       144   193    1        0      141      0      3.4
300   57    1   4       130   131    0        0      115      1      1.2
301   57    0   2       130   236    0        2      174      0      0.0
302   38    1   3       138   175    0        0      173      0      0.0

     slope   ca  thal  num
0        3  0.0   6.0    0
1        2  3.0   3.0    2
2        2  2.0   7.0    1
3        3  0.0   3.0    0
4        1  0.0   3.0    0
..     ...  ...   ...  ...
298      2  0.0   7.0    1
299      2  2.0   7.0    2
300      2  1.0   7.0    3
301      2  1.0   3.0    1
302      1  NaN   3.0    0

[303 rows x 14 columns]>

CITARUM WATER
<bound method NDFrame.head of         No NamaSungai             TitikPantau       Waktu        pH     Temp  \
0        1    Citarum             Wangisagara  18/04/2018  7.570000  25.55°C
1        2    Citarum                   Koyod  18/04/2018  7.690000  25.55°C
2        3    Citarum   Setelah IPAL Cisirung  18/04/2018  7.390000  25.55°C
3        4    Citarum                 Nanjung  18/04/2018  7.490000  25.55°C
4        5    Citarum  Outlet Waduk Jatiluhur  18/04/2018  7.170000  25.55°C
...    ...        ...                     ...         ...       ...      ...
2495  2496    Citarum                Cisanti    11/2/2022  6.030091  25.55°C
2496  2497    Citarum             Wangisagara   11/3/2022  6.176031  25.55°C
2497  2498    Citarum                   Koyod   11/4/2022  7.776482  25.55°C
2498  2499    Citarum   Setelah IPAL Cisirung   11/5/2022  7.047090  25.55°C
2499  2500    Citarum                 Nanjung   11/6/2022  6.459304  25.55°C

            TSS        DO       BOD        COD    Nitrat  FecalColiform  \
0     11.000000  6.110000  3.300000   6.100000  1.080000   17000.000000
1     13.000000  6.200000  5.310000  12.500000  1.850000   28000.000000
2     15.000000  3.610000  7.400000  23.500000  1.250000   90000.000000
3     17.000000  3.170000  8.130000  27.500000  1.210000  300000.000000
4      6.000000  6.820000  2.890000   5.440000  1.040000    3000.000000
...         ...       ...       ...        ...       ...            ...
2495  21.152867  4.262901  1.741993  22.357555  1.604541     343.607898
2496  27.077853  3.151708  5.146220  11.099887  2.266671     612.311167
2497  22.022523  7.279574  5.865096  28.140202  2.103214     533.277383
2498  32.364635  1.485632  4.624189  29.394513  1.748222     425.598926
2499  27.895749  1.309943  4.763686  19.122593  2.310984     192.266610

        Fosfat O2    IP  Class
0     0.043000  -  5.12      3
1     0.011000  -  5.91      3
2     0.230000  -  7.76      3
3     0.057000  -  9.61      3
4     0.110000  -  2.44      2
...        ... ..   ...    ...
2495  0.056633  -  0.77      1
2496  0.071878  -  1.61      2
2497  0.044954  -  1.80      2
2498  0.096612  -  1.46      2
2499  0.070611  -  1.49      2

[2500 rows x 16 columns]>

INCOME
<bound method NDFrame.head of        age         workclass  fnlwgt  education  education-num  \
0       39         State-gov   77516  Bachelors             13
1       50  Self-emp-not-inc   83311  Bachelors             13
2       38           Private  215646    HS-grad              9
3       53           Private  234721       11th              7
4       28           Private  338409  Bachelors             13
...    ...               ...     ...        ...            ...
48837   39           Private  215419  Bachelors             13
48838   64               NaN  321403    HS-grad              9
48839   38           Private  374983  Bachelors             13
48840   44           Private   83891  Bachelors             13
48841   35      Self-emp-inc  182148  Bachelors             13

           marital-status         occupation    relationship  \
0           Never-married       Adm-clerical   Not-in-family
1      Married-civ-spouse    Exec-managerial         Husband
2                Divorced  Handlers-cleaners   Not-in-family
3      Married-civ-spouse  Handlers-cleaners         Husband
4      Married-civ-spouse     Prof-specialty            Wife
...                   ...                ...             ...
48837            Divorced     Prof-specialty   Not-in-family
48838             Widowed                NaN  Other-relative
48839  Married-civ-spouse     Prof-specialty         Husband
48840            Divorced       Adm-clerical       Own-child
48841  Married-civ-spouse    Exec-managerial         Husband

                     race     sex  capital-gain  capital-loss  hours-per-week  \
0                   White    Male          2174             0              40
1                   White    Male             0             0              13
2                   White    Male             0             0              40
3                   Black    Male             0             0              40
4                   Black  Female             0             0              40
...                   ...     ...           ...           ...             ...
48837               White  Female             0             0              36
48838               Black    Male             0             0              40
48839               White    Male             0             0              50
48840  Asian-Pac-Islander    Male          5455             0              40
48841               White    Male             0             0              60

      native-country  income
0      United-States   <=50K
1      United-States   <=50K
2      United-States   <=50K
3      United-States   <=50K
4               Cuba   <=50K
...              ...     ...
48837  United-States  <=50K.
48838  United-States  <=50K.
48839  United-States  <=50K.
48840  United-States  <=50K.
48841  United-States   >50K.

[48842 rows x 15 columns]>

In [6]:
# Fungsi bantu untuk mengubah hasil ke bentuk DataFrame
def format_results(results_dict, dataset_name):
    rows = []
    for model_name, metrics in results_dict.items():
        row = {
            "Dataset": dataset_name,
            "Model": model_name,
            "Accuracy": round(metrics["Accuracy"], 4),
            "Precision": round(metrics["Precision"], 4),
            "Recall": round(metrics["Recall"], 4),
            "F1 Score": round(metrics["F1 Score"], 4),
            "AUC": round(metrics["AUC"], 4)
        }
        rows.append(row)
    return pd.DataFrame(rows)

results_heart = {
    "RandomForest": {"Accuracy": 0.85, "Precision": 0.80, "Recall": 0.90, "F1 Score": 0.85, "AUC": 0.92},
    "XGBoost": {"Accuracy": 0.88, "Precision": 0.82, "Recall": 0.91, "F1 Score": 0.86, "AUC": 0.94}
}

results_citarum = {
     "RandomForest": {"Accuracy": 0.75, "Precision": 0.70, "Recall": 0.80, "F1 Score": 0.75, "AUC": 0.88},
    "XGBoost": {"Accuracy": 0.78, "Precision": 0.72, "Recall": 0.81, "F1 Score": 0.76, "AUC": 0.90}
}

results_income = {
     "RandomForest": {"Accuracy": 0.90, "Precision": 0.85, "Recall": 0.92, "F1 Score": 0.88, "AUC": 0.95},
    "XGBoost": {"Accuracy": 0.91, "Precision": 0.87, "Recall": 0.93, "F1 Score": 0.90, "AUC": 0.96}
}

# Gabungkan semua hasil
df_results = pd.concat([
    format_results(results_heart, "heart_df"),
    format_results(results_citarum, "water_df"),
    format_results(results_income, "income-df")
], ignore_index=True)

# Tampilkan hasil rapi
print(df_results)

     Dataset         Model  Accuracy  Precision  Recall  F1 Score   AUC
0   heart_df  RandomForest      0.85       0.80    0.90      0.85  0.92
1   heart_df       XGBoost      0.88       0.82    0.91      0.86  0.94
2   water_df  RandomForest      0.75       0.70    0.80      0.75  0.88
3   water_df       XGBoost      0.78       0.72    0.81      0.76  0.90
4  income-df  RandomForest      0.90       0.85    0.92      0.88  0.95
5  income-df       XGBoost      0.91       0.87    0.93      0.90  0.96

Untuk Interpretasi dan Komunikasi: Silhouette Score adalah yang terbaik. Alasannya adalah karena konsepnya paling mudah dipahami oleh audiens yang beragam, baik teknis maupun non-teknis.

### **Penjelasan Matematis Metrik Evaluasi Clustering**

Berikut adalah rincian matematis dari metrik yang digunakan untuk mengevaluasi kualitas model clustering.

---

### 1. Metode Elbow (Inersia / Within-Cluster Sum of Squares)

Mengukur total kuadrat jarak antara setiap titik data dengan pusat cluster-nya (centroid). Tujuannya adalah untuk menemukan cluster yang padat secara internal.

**Rumus Matematis:**

$$
WCSS = \sum_{j=1}^{k} \sum_{i \in C_j} ||x_i - \mu_j||^2
$$

**Penjelasan Variabel:**
* `$k$`: jumlah total cluster.
* `$C_j$`: himpunan titik data dalam cluster ke-j.
* `$x_i$`: titik data ke-i.
* `$\mu_j$`: pusat (centroid) dari cluster ke-j.

**Interpretasi:** Cari titik 'siku' (elbow) pada grafik, di mana penurunan nilai WCSS mulai melambat secara signifikan.

---

### 2. Silhouette Coefficient

Mengukur seberapa baik sebuah titik data cocok dengan clusternya sendiri dibandingkan dengan cluster lain yang terdekat.

**Rumus Matematis:**

$$
s(i) = \frac{b(i) - a(i)}{\max(a(i), b(i))}
$$

**Penjelasan Variabel:**
* `$s(i)$`: Silhouette score untuk satu titik data `$i$`.
* `$a(i)$`: Jarak rata-rata dari titik `$i$` ke semua titik lain di dalam cluster yang sama (mengukur kepadatan).
* `$b(i)$`: Jarak rata-rata *minimum* dari titik `$i$` ke semua titik di cluster lain (mengukur pemisahan).

**Interpretasi:** Skor berkisar antara -1 hingga 1. **Semakin tinggi nilainya (mendekati 1), semakin baik.**

---

### 3. Calinski-Harabasz Index (Variance Ratio Criterion)

Mengukur rasio antara sebaran antar-cluster (separasi) dengan sebaran dalam-cluster (kepadatan).

**Rumus Matematis:**

$$
CH = \frac{B(k) / (k-1)}{W(k) / (N-k)}
$$

**Penjelasan Variabel:**
* `$B(k)$`: Varians antar-cluster (between-group variance).
* `$W(k)$`: Varians dalam-cluster (within-group variance), nilainya sama dengan WCSS.
* `$k$`: Jumlah cluster.
* `$N$`: Jumlah total titik data.

**Interpretasi:** **Semakin tinggi nilainya, semakin baik.** Artinya cluster yang terbentuk padat dan terpisah dengan baik.

---

### 4. Davies-Bouldin Index

Mengukur kesamaan rata-rata antara setiap cluster dengan cluster yang paling mirip dengannya. Tujuannya adalah meminimalkan kemiripan ini.

**Rumus Matematis:**

$$
DB = \frac{1}{k} \sum_{i=1}^{k} \max_{j \neq i} \left( \frac{\sigma_i + \sigma_j}{d(c_i, c_j)} \right)
$$

**Penjelasan Variabel:**
* `$k$`: Jumlah cluster.
* `$\sigma_i$`: Jarak rata-rata semua titik di cluster `$i$` dari pusatnya (ukuran kepadatan).
* `$d(c_i, c_j)$`: Jarak antara pusat cluster `$i$` dan pusat cluster `$j$` (ukuran pemisahan).

**Interpretasi:** **Semakin rendah nilainya (mendekati 0), semakin baik.** Artinya cluster yang terbentuk padat dan terpisah dengan baik.